[package]
name = "pyo3-testing"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyo3testing"
path = "src/lib.rs"
crate-type = ["rlib"]  # cdylib required for python import, rlib required for rust tests.

[dependencies]
quote = "1.0.35"
proc-macro2 = "1.0.74"
syn = "2.0.55"